# Generated by Django 2.2.5 on 2019-09-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=10)),
                ('comentario', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('IN', 'Iniciado'), ('PR', 'EnProgreso'), ('FI', 'Finalizado')], default='IN', max_length=2)),
            ],
        ),
    ]
