# Generated by Django 2.2.5 on 2019-09-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
