# Generated by Django 2.2.5 on 2019-09-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0001_initial'),
        ('Reclamos', '0002_auto_20190918_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inmuebles.Inmueble'),
        ),
    ]
