# Generated by Django 2.2.5 on 2019-09-22 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reclamos', '0004_reclamo_creado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='lugar',
            new_name='inmueble',
        ),
    ]
